---
- include: playbooks/common.yml
- include: playbooks/zookeeper.yml
- include: playbooks/sparkmaster.yml
- include: playbooks/sparkworker.yml
- include: playbooks/ngxapp.yml
- include: playbooks/nagiosplugins.yml
