---
- name: create the journalnode directory
  file: path={{ hadoop_dfs_dir_parent }}{{ hadoop_dfs_dir_jn }} owner=hdfs group=hdfs state=directory

- name: install hadoop-hdfs-journalnode via yum
  yum: name=hadoop-hdfs-journalnode-{{hadoop_journalnode_version}} state=present
  notify:
    - restart hadoop-hdfs-journalnode
