---
- name: Common
  hosts: all
  remote_user: "{{ ansible_remoteuser }}"
  become: yes
  become_method: sudo
  roles:
    - { role: dnshostfile, when: "'vagrant' in group_names" }
    - oraclejava
    - cdh_rpm
