---
- name: create the datanode directory
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  with_items: "{{ hadoop_dfs_dir_dn }}"

- name: install hadoop-hdfs-datanode via yum
  yum: name=hadoop-hdfs-datanode-{{hadoop_datanode_version}} state=present
  notify:
    - restart hadoop-hdfs-datanode
